### ISSUE TITLE
Error in Cron Scheduler on Ubuntu 20.04 

### ISSUE THREAD

**Issue by sagewhocodes** [mayahq/maya-red-system-utils#6]
1. Open Maya Command Bar
2. Schedule something with scheduler.
![image](https://user-images.githubusercontent.com/54904272/122723167-43d3a700-d290-11eb-9006-b09dec3a84b6.png)

**Comment by sibeshkar** [comment]
```
sudo apt-get update
sudo apt-get install libnotify-bin
```
Can you try running these once and then trying?
